### ISSUE TITLE
Installation error on kali

### ISSUE THREAD

**Issue by yicheng-w** [elc1798/aptproxyget#1]
"mkdir: cannot create directory `/root/.aptproxyget': File exists
**install.sh: 15: install.sh: source: not found**
aptproxyget has been successfully installed.
Commands:
        -c      Checks /etc/apt/apt.conf.d/01proxy existence and outputs the contents of the file
        -a      Adds /etc/apt/apt.conf.d/01proxy and the rules for the NYCBOE proxy
        -r      Removed /etc/apt/apt.conf.d/01proxy if it exists
        -h      Displays this message"

**Comment by elc1798** [comment]
This isn't meant for kali -.- Go away Yicheng LOL I'll make a kali version
